import { useNavigate } from 'react-router-dom';
import LandingHeader from './LandingHeader';
import {
  Zap, ArrowRight, CheckCircle, Star, Sparkles, BrainCircuit,
  Target, Code, Award, Users, BarChart3, MessageSquare,
  Globe, BookOpen, Rocket, TrendingUp, Shield, Clock
} from 'lucide-react';

const features = [
  { icon: <BrainCircuit className="w-6 h-6" />, title: 'AI Role Analysis', desc: 'Upload your resume and get a detailed skill-gap analysis instantly. Know exactly what is missing for your dream job.' },
  { icon: <Target className="w-6 h-6" />, title: 'Personalised Roadmap', desc: 'Get a custom step-by-step learning path generated by AI, tailored to your specific career goal and current level.' },
  { icon: <Code className="w-6 h-6" />, title: 'Live Project Dashboard', desc: 'Work on real-world AI-curated projects with guided curricula. Build your portfolio while learning on the job.' },
  { icon: <Sparkles className="w-6 h-6" />, title: 'Tech Stack Generator', desc: 'Know precisely which programming languages, frameworks, and tools to learn with step-by-step install guides.' },
  { icon: <MessageSquare className="w-6 h-6" />, title: 'AI Interview Coach', desc: 'Practise with real interview questions and get instant AI feedback on your answers before the actual interview.' },
  { icon: <Award className="w-6 h-6" />, title: 'Achievements & XP', desc: 'Stay motivated with a gamified XP system. Earn badges for completing tasks, streaks, and career milestones.' },
  { icon: <BookOpen className="w-6 h-6" />, title: 'Resources Hub', desc: 'Smart AI search for courses, tutorials, articles, and documentation all ranked by relevance to your role.' },
  { icon: <Globe className="w-6 h-6" />, title: 'Multiple Career Workspaces', desc: 'Exploring more than one career? Switch between multiple career contexts without losing your progress in each.' },
];

const stats = [
  { value: '50+', label: 'Career Paths Supported' },
  { value: '1,000+', label: 'AI-Generated Projects' },
  { value: '98%', label: 'User Satisfaction' },
  { value: '10x', label: 'Faster Career Growth' },
];

const testimonials = [
  { name: 'Aarav Sharma', role: 'Junior Software Engineer', text: 'FindStreak gave me a clear roadmap when I had no idea where to start. Within 3 months I landed my first dev job!', stars: 5 },
  { name: 'Priya Nair', role: 'Data Analyst to ML Engineer', text: 'The AI skill gap analysis was spot-on. It showed me exactly what I needed to learn to transition into Machine Learning.', stars: 5 },
  { name: "Liam O'Brien", role: 'DevOps Engineer', text: 'The Tech Stack Guide feature is incredible. I got a step-by-step setup guide for Docker and Kubernetes in seconds!', stars: 5 },
];

const benefits = [
  'No guesswork — AI tells you exactly what to learn next',
  'Real projects to build a portfolio that impresses recruiters',
  'Interview prep with live AI feedback on every answer',
  'Track streaks and earn XP to stay motivated daily',
  'Works for all levels — from complete beginners to seniors',
  'Switch between multiple career tracks without losing progress',
];

const whyCards = [
  { icon: <TrendingUp className="w-5 h-5 text-teal-600" />, title: 'Track Your Progress', desc: 'See your skill level grow week over week with visual progress indicators and XP scores.' },
  { icon: <Shield className="w-5 h-5 text-teal-600" />, title: 'Career-Safe Learning', desc: 'Every project and resource recommended is vetted for real-world relevance, not just theory.' },
  { icon: <Clock className="w-5 h-5 text-teal-600" />, title: 'Learn at Your Own Pace', desc: 'No deadlines. No pressure. Your roadmap adapts to your schedule even if you only have 30 mins a day.' },
  { icon: <Rocket className="w-5 h-5 text-teal-600" />, title: 'Interview-Ready in Weeks', desc: 'Our mock interview system prepares you for real technical and behavioural questions with AI scored feedback.' },
  { icon: <Users className="w-5 h-5 text-teal-600" />, title: 'Built for All Levels', desc: 'Whether you are switching careers or levelling up from junior to senior, FindStreak scales to your needs.' },
  { icon: <BarChart3 className="w-5 h-5 text-teal-600" />, title: 'Data-Driven Decisions', desc: 'AI analyses thousands of real job postings to give you accurate, industry-relevant recommendations.' },
];

export default function LandingHome() {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen font-sans bg-white text-slate-900">
      <LandingHeader />

      {/* Hero */}
      <section className="relative pt-28 pb-24 px-4 overflow-hidden bg-gradient-to-br from-slate-50 via-teal-50/40 to-emerald-50/30">
        <div className="absolute inset-0 overflow-hidden pointer-events-none">
          <div className="absolute -top-20 -right-40 w-[600px] h-[600px] bg-teal-200/20 rounded-full blur-3xl" />
          <div className="absolute -bottom-40 -left-20 w-[400px] h-[400px] bg-emerald-200/20 rounded-full blur-3xl" />
        </div>

        <div className="max-w-5xl mx-auto text-center relative z-10">
          <div className="inline-flex items-center gap-2 px-4 py-2 bg-teal-50 border border-teal-200 rounded-full text-teal-700 text-sm font-bold mb-8 shadow-sm">
            <Zap className="w-4 h-4 text-teal-500" />
            AI-Powered Career Acceleration Platform
          </div>

          <h1 className="text-5xl md:text-7xl font-black text-slate-900 leading-tight mb-6 tracking-tight">
            Land Your{' '}
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-teal-600 to-emerald-500">
              Dream Tech Job
            </span>{' '}
            Faster
          </h1>

          <p className="text-xl md:text-2xl text-slate-600 max-w-3xl mx-auto mb-10 leading-relaxed">
            FindStreak is your AI career co-pilot. It analyses your skills, builds a personalised learning roadmap, suggests real projects, and preps you for interviews all in one platform.
          </p>

          <div className="flex flex-col sm:flex-row gap-4 justify-center mb-12">
            <button
              onClick={() => navigate('/signup')}
              className="group px-8 py-4 bg-gradient-to-r from-teal-600 to-emerald-600 hover:from-teal-700 hover:to-emerald-700 text-white rounded-2xl font-bold text-lg shadow-xl hover:shadow-2xl transition-all flex items-center justify-center gap-2"
            >
              Get Started Free
              <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
            </button>
            <button
              onClick={() => navigate('/how-it-works')}
              className="px-8 py-4 border-2 border-teal-200 text-teal-700 rounded-2xl font-bold text-lg hover:bg-teal-50 transition-all"
            >
              See How It Works
            </button>
          </div>

          <div className="flex flex-wrap justify-center gap-3">
            {['No credit card required', 'Free to start', 'AI-powered insights'].map(t => (
              <div key={t} className="flex items-center gap-1.5 text-sm text-slate-500 font-medium">
                <CheckCircle className="w-4 h-4 text-emerald-500" />
                {t}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Stats */}
      <section className="py-16 px-4 bg-gradient-to-r from-teal-600 to-emerald-600">
        <div className="max-w-5xl mx-auto grid grid-cols-2 md:grid-cols-4 gap-8">
          {stats.map(s => (
            <div key={s.label} className="text-center">
              <div className="text-4xl md:text-5xl font-black text-white mb-1">{s.value}</div>
              <div className="text-teal-100 text-sm font-semibold">{s.label}</div>
            </div>
          ))}
        </div>
      </section>

      {/* Features */}
      <section className="py-24 px-4 bg-slate-50">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-16">
            <span className="text-teal-600 font-bold text-sm uppercase tracking-widest">Everything You Need</span>
            <h2 className="text-4xl md:text-5xl font-black mt-3 text-slate-900">Your Complete Career Toolkit</h2>
            <p className="text-slate-500 text-lg mt-4 max-w-2xl mx-auto">Everything from skill analysis to interview prep built for ambitious tech professionals ready to level up.</p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {features.map((f, i) => (
              <div key={i} className="bg-white rounded-2xl p-6 border border-slate-100 shadow-sm hover:shadow-lg hover:border-teal-200 transition-all group">
                <div className="w-12 h-12 bg-gradient-to-br from-teal-50 to-emerald-100 rounded-xl flex items-center justify-center mb-4 text-teal-600 group-hover:from-teal-500 group-hover:to-emerald-500 group-hover:text-white transition-all">
                  {f.icon}
                </div>
                <h3 className="font-bold text-slate-900 mb-2 text-[15px]">{f.title}</h3>
                <p className="text-slate-500 text-[13px] leading-relaxed">{f.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Why FindStreak */}
      <section className="py-24 px-4">
        <div className="max-w-6xl mx-auto flex flex-col lg:flex-row items-center gap-16">
          <div className="flex-1">
            <span className="text-teal-600 font-bold text-sm uppercase tracking-widest">Why FindStreak?</span>
            <h2 className="text-4xl md:text-5xl font-black mt-3 mb-6 text-slate-900">Stop Guessing. Start Growing.</h2>
            <p className="text-slate-600 text-lg mb-8 leading-relaxed">
              Most developers waste months figuring out <em>what</em> to learn next. FindStreak eliminates every second of that confusion. Our AI analyses your exact situation and tells you the most direct path to your career goal.
            </p>
            <div className="space-y-3">
              {benefits.map((b, i) => (
                <div key={i} className="flex items-start gap-3">
                  <div className="w-5 h-5 rounded-full bg-emerald-100 flex items-center justify-center flex-shrink-0 mt-0.5">
                    <CheckCircle className="w-3.5 h-3.5 text-emerald-600" />
                  </div>
                  <p className="text-slate-700 font-medium text-[15px]">{b}</p>
                </div>
              ))}
            </div>
            <button
              onClick={() => navigate('/signup')}
              className="mt-10 px-7 py-3.5 bg-gradient-to-r from-teal-600 to-emerald-600 text-white rounded-xl font-bold shadow-lg hover:shadow-xl transition-all flex items-center gap-2"
            >
              Start Your Journey Free <ArrowRight className="w-4 h-4" />
            </button>
          </div>

          <div className="flex-1 grid grid-cols-1 gap-4">
            {whyCards.map((c, i) => (
              <div key={i} className="flex items-start gap-4 p-4 bg-slate-50 rounded-xl border border-slate-100">
                <div className="w-10 h-10 rounded-lg bg-teal-50 flex items-center justify-center flex-shrink-0">{c.icon}</div>
                <div>
                  <h4 className="font-bold text-slate-900 text-sm mb-0.5">{c.title}</h4>
                  <p className="text-slate-500 text-xs leading-relaxed">{c.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section className="py-24 px-4 bg-gradient-to-br from-teal-50 to-emerald-50/50">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-14">
            <span className="text-teal-600 font-bold text-sm uppercase tracking-widest">Real Results</span>
            <h2 className="text-4xl font-black mt-3 text-slate-900">Loved by Developers Worldwide</h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {testimonials.map((t, i) => (
              <div key={i} className="bg-white rounded-2xl p-6 shadow-sm border border-teal-100 hover:shadow-md transition-all">
                <div className="flex mb-3">
                  {Array(t.stars).fill(0).map((_, j) => (
                    <Star key={j} className="w-4 h-4 text-amber-400 fill-amber-400" />
                  ))}
                </div>
                <p className="text-slate-600 text-sm leading-relaxed mb-5 italic">"{t.text}"</p>
                <div>
                  <p className="font-bold text-slate-900 text-sm">{t.name}</p>
                  <p className="text-teal-600 text-xs font-semibold">{t.role}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-24 px-4 bg-gradient-to-r from-teal-700 to-emerald-700">
        <div className="max-w-3xl mx-auto text-center">
          <h2 className="text-4xl md:text-5xl font-black text-white mb-6">Ready to Build Your Dream Career?</h2>
          <p className="text-teal-100 text-xl mb-10 leading-relaxed">Join thousands of developers who are using FindStreak to accelerate their careers. Start free no credit card needed.</p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <button
              onClick={() => navigate('/signup')}
              className="px-8 py-4 bg-white text-teal-700 rounded-2xl font-bold text-lg shadow-xl hover:shadow-2xl transition-all flex items-center justify-center gap-2"
            >
              Create Your Free Account <ArrowRight className="w-5 h-5" />
            </button>
            <button
              onClick={() => navigate('/signin')}
              className="px-8 py-4 border-2 border-white/40 text-white rounded-2xl font-bold text-lg hover:bg-white/10 transition-all"
            >
              Login to My Account
            </button>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="py-8 px-4 bg-slate-900 text-slate-400 text-center">
        <div className="flex items-center justify-center gap-2 mb-3">
          <div className="w-7 h-7 bg-gradient-to-br from-teal-500 to-emerald-600 rounded-lg flex items-center justify-center">
            <Zap className="w-4 h-4 text-white" />
          </div>
          <span className="text-white font-bold text-lg">FindStreak</span>
        </div>
        <p className="text-sm">© 2026 FindStreak. Empowering tech careers worldwide.</p>
        <div className="flex justify-center gap-6 mt-3 text-xs">
          {['Home', 'About', 'How It Works', 'Contact'].map(l => (
            <button key={l} className="hover:text-teal-400 transition-colors">{l}</button>
          ))}
        </div>
      </footer>
    </div>
  );
}
